#!/usr/bin/env python3
"""Plot observed NICER lightcurve with first and best model lightcurves."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def load_two_col(path: Path) -> tuple[np.ndarray, np.ndarray]:
    data = np.loadtxt(path)
    if data.ndim == 1:
        if data.size != 2:
            raise ValueError(f"Expected 2 columns in {path}, got shape {data.shape}")
        data = data.reshape(1, 2)
    if data.shape[1] != 2:
        raise ValueError(f"Expected 2 columns in {path}, got {data.shape[1]}")
    return data[:, 0], data[:, 1]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot observed NICER and best-model lightcurves generated by Fortran run."
    )
    parser.add_argument(
        "--nicer",
        default="nicer_profile.dat",
        help="Path to observed output file (default: nicer_profile.dat)",
    )
    parser.add_argument(
        "--model",
        default="output/best_model_lightcurve.dat",
        help="Path to best-model output file (default: best_model_lightcurve.dat)",
    )
    parser.add_argument(
        "--out",
        default="images/lightcurves_comparison.png",
        help="Output image path (default: lightcurves_comparison.png)",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display interactive plot window in addition to saving image.",
    )
    parser.add_argument(
        "--background",
        type=float,
        default=13500.0,  # Set to the default used in Fortran
        help="Background value to subtract from observed light curve (default: 13500.0)",
    )
    args = parser.parse_args()

    nicer_path = Path(args.nicer)
    model_path = Path(args.model)

    print(f"[plot] Looking for NICER file: {nicer_path.resolve()}")
    if not nicer_path.exists():
        print(f"[plot][error] NICER file not found: {nicer_path.resolve()}")
        sys.exit(1)

    print(f"[plot] Looking for best-model file: {model_path.resolve()}")
    if not model_path.exists():
        print(f"[plot][error] Best-model file not found: {model_path.resolve()}")
        sys.exit(1)

    print("[plot] Found all input files. Loading data...")

    x_nicer, y_nicer = load_two_col(nicer_path)
    y_nicer = y_nicer - args.background
    x_model, y_model = load_two_col(model_path)

    fig, ax = plt.subplots(figsize=(9, 5))
    ax.plot(x_nicer, y_nicer, "o-", ms=3, lw=1.2, label="NICER (background-subtracted)")
    ax.plot(x_model, y_model, "-", lw=1.8, label="Best model lightcurve")
    ax.set_xlabel("Phase / bin")
    ax.set_ylabel("Counts")
    ax.set_title("NICER vs Best Model Lightcurve")
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()

    out_path = Path(args.out)
    fig.savefig(out_path, dpi=150)
    print(f"[plot] Saved plot to: {out_path.resolve()}")

    if args.show:
        plt.show()


if __name__ == "__main__":
    main()

